### PR TITLE
Adding support for maxActiveInstances optional field for activities

### PR DESCRIPTION
**Pull request by gtitievsky**
all of the activities in http://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-object-activities.html contain maxActiveInstances field. Adding it to be able to create a pipeline with that field.

### CODE REVIEW

**Comment by sethyates** [comment]
Please review and fix test failure.

**Comment by sethyates** [comment]
As we still build for Scala 2.10, case classes are limited to 22 members by Scala.  So adding this field has pushed some case classes over that limit.  Please refactor by turning them into normal classes:

```
[error] /home/travis/build/krux/hyperion/core/src/main/scala/com/krux/hyperion/aws/AdpActivities.scala:237: Implementation restriction: case classes cannot have more than 22 parameters.
[error] case class AdpHadoopActivity (
[error]            ^
[error] /home/travis/build/krux/hyperion/core/src/main/scala/com/krux/hyperion/aws/AdpActivities.scala:456: Implementation restriction: case classes cannot have more than 22 parameters.
[error] case class AdpShellCommandActivity (
[error]            ^
```

**Comment by gtitievsky** [comment]
Refactored case classes into regular classes (as well as tests and classes that rely on them)

**Comment by realstraw** [comment]
Thank you @gtitievsky 

Can you update the version number to `3.3.0` in `build.sbt`, update `CHANGELOG.md` accordingly, and if you like, add yourself to `CONTRIBUTORS`? I'll merge afterwards.

**Comment by gtitievsky** [comment]
Done. Thanks @realstraw

**Comment by gtitievsky** [comment]
@realstraw : could you please publish the latest to maven? our development project needs it. Thanks.

**Comment by realstraw** [comment]
@gtitievsky It should be done automatically by travis once it's merged. Also I've just tested at my end that it does retrieve 3.3.0 without any problem.

**Comment by gtitievsky** [comment]
@realstraw http://search.maven.org/#search%7Cgav%7C2%7Cg%3A%22com.krux%22%20AND%20a%3A%22hyperion_2.11%22 doesn't show it

**Comment by realstraw** [comment]
it probably takes a while to show up, but I can find it here: https://repo1.maven.org/maven2/com/krux/hyperion_2.11/3.3.0/

**Pull request merged**
