### PR TITLE
[552] : Adds support to execute custom script before running JarActivity

### PR DESCRIPTION
**Pull request by ssharma**
There is a need to increase process `ulimit` for a given session before executing `JarActivity`. This PR adds support to inject custom script before executing jar command

### CODE REVIEW

**Comment by realstraw** [comment]
The use case seems like resource based configuration. Isn't it better to just build an AMI with ulimit pre-configured?

**Comment by ssharma** [comment]
Yes, we can do that too. Just felt that would be more of a maintenance issue for a trivial ask

**Comment by ssharma** [comment]
@realstraw We need to unblock soon. So, if this isn't something you're comfortable with, we'll go ahead and create custom AMI.

**Comment by prashuj** [comment]
@realstraw  as you know it.. building and maintaining our own custom AMI's is a pain

**Comment by realstraw** [comment]
@prashuj @prashuj It's no longer a pain to build and maintain AMIs, let's take the discussion offline from public git PR.

**Comment by ssharma** [comment]
Not doing

**Pull request closed without merging**
