### PR TITLE
(Fixes #64) Supports non-default region

### LINKED ISSUE #64: Ability to create pipelines in non-default region

### PR DESCRIPTION
**Pull request by sethyates**

### CODE REVIEW

**Comment by realstraw** [comment]
Should we make the client use `hyperion.aws.access_key_id` and `hyperion.aws.access_key_secret` as well?

**Comment by sethyates** [comment]
I think the default credentials provider chain is fine (apart from maybe using STS to assume role). If anything, this should be specified from outside the app/configuration for security reasons.

**Comment by sethyates** [comment]
Plus it would be a bit difficult to do this reliably given the workflow can override configuration.

**Comment by realstraw** [comment]
OK :+1:

**Pull request closed without merging**
